/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Paquete.Clases.*;
import Paquete.gestion.Gestion;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author redes
 */
public class MostrarTable extends javax.swing.JFrame {

    /**
     * Creates new form MostrarTable
     */
    private DefaultTableModel modelo;  
    private Gestion ref2;
    
    public MostrarTable() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Tipo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Nivel");
        modelo.addColumn("Adquisición");
        modelo.addColumn("Poder.Max");
        this.jTable1.setModel(modelo);
        
    }

    public Gestion getRef2() {
        return ref2;
    }

    public void setRef2(Gestion ref2) {
        this.ref2 = ref2;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new ImageFondo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotonEliminar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        PanelEvo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TextoEvoUno = new javax.swing.JTextField();
        TextoEvoDos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POKÉDEX");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 470, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Pokebola.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 60, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Volver.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Para Cargar los Datos Presione la Pokebola ------------------->");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        BotonEliminar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 40));

        BotonBuscar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        BotonBuscar.setText("Pokémon más Poderoso");
        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 40));

        PanelEvo.setBackground(new java.awt.Color(36, 169, 214));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EVOLUCIONAR");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelEvoLayout = new javax.swing.GroupLayout(PanelEvo);
        PanelEvo.setLayout(PanelEvoLayout);
        PanelEvoLayout.setHorizontalGroup(
            PanelEvoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEvoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelEvoLayout.setVerticalGroup(
            PanelEvoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(PanelEvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 140, 50));

        TextoEvoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoEvoUnoActionPerformed(evt);
            }
        });
        jPanel2.add(TextoEvoUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 140, 30));
        jPanel2.add(TextoEvoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 140, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Inventario1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, 50));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre del Pokémon");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre Evolucionado");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ver");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 60, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("Inventario");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        CargarDatosTabla();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Ventana Menu = new Ventana();
        Menu.setRef(ref2);
        Menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel2MouseClicked

    private void TextoEvoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoEvoUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoEvoUnoActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        PanelEvo.setBackground(new Color(247,235,55));
        jLabel4.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        PanelEvo.setBackground(new Color(36,169,214));
        jLabel4.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jLabel4MouseExited

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
        int Posi = jTable1.getSelectedRow();
        if(Posi>=0){
            modelo.removeRow(Posi);
            ref2.Eliminar(Posi);
            CargarDatosTabla();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila :)");
        }
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        if(this.jTable1.getRowCount()>0)
        {
            ref2.BuscarMayorPoder();
        }
        else{
            JOptionPane.showMessageDialog(null, "¡Hey!, primero registre un pokémon");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    String poke = TextoEvoUno.getText();
    String pokeEvo = TextoEvoDos.getText();
    
    if(poke.equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(null, "¡Hey!, primero ingrese el pokémon que desea evolucionar");
    }
    else if(pokeEvo.equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(null, "No se olvide de renombrar su pokémon :)");
    }
    else{
        ref2.EvolucionarPokemon(poke, pokeEvo);
    }
    CargarDatosTabla();
        
        
    /*Pokemon[] arreEvo = ref2.getArreglo();
    for(int i=0;i<ref2.getPuntero();i++){
        if(arreEvo[i] instanceof TipoFantasma){
            if(SI.isSelected()){
                String poke = TextoEvoUno.getText();
                String pokeEvo = TextoEvoDos.getText();
                ref2.EvolucionarPokemon(poke, pokeEvo);
            }
            if(NO.isSelected()){
                JOptionPane.showMessageDialog(null, "Su Pokémon requiere una Piedra Evolutiva :(");
            }
        }
        if(arreEvo[i] instanceof TipoPsiquico){
            if(SI.isSelected()){
                String poke = TextoEvoUno.getText();
                String pokeEvo = TextoEvoDos.getText();
                ref2.EvolucionarPokemon(poke, pokeEvo);
            }
            if(NO.isSelected()){
                JOptionPane.showMessageDialog(null, "Su Pokémon requiere una Piedra Evolutiva :(");
            }
        }
        else{
            String poke = TextoEvoUno.getText();
            String pokeEvo = TextoEvoDos.getText();
            ref2.EvolucionarPokemon(poke, pokeEvo);
        }
    }*/
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        ref2.VerPokebolas();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JPanel PanelEvo;
    private javax.swing.JTextField TextoEvoDos;
    private javax.swing.JTextField TextoEvoUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    class ImageFondo extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("FondoPokedex.jpeg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
        
        
    }
    
    public void CargarDatosTabla()
    {
        int filas = this.jTable1.getRowCount();
        for(int i=0;i<filas;i++)
        {
            modelo.removeRow(0);
        }
        
        String[] datos = new String[5];
        Pokemon[] arreglo = ref2.getArreglo();
        for(int i=0;i<ref2.getPuntero();i++)
        {
            if(arreglo[i] instanceof TipoAgua)
            {
                datos[0]="Agua";
            }
            else if(arreglo[i] instanceof TipoFuego)
            {
                datos[0]="Fuego";
            }
            else if(arreglo[i] instanceof TipoTierra)
            {
                datos[0]="Tierra";
            }
            else if(arreglo[i] instanceof TipoPlanta)
            {
                datos[0]="Planta";
            }
            else if(arreglo[i] instanceof TipoElectrico)
            {
                datos[0]="Eléctrico";
            }
            else if(arreglo[i] instanceof TipoPsiquico)
            {
                datos[0]="Psíquico";
            }
            else if(arreglo[i] instanceof TipoFantasma)
            {
                datos[0]="Fantasma";
            }
            
            datos[1] = arreglo[i].getNombre();
            datos[2] = String.valueOf(arreglo[i].getNivel());
            datos[3] = arreglo[i].getFechaDeAdqui();
            datos[4] = String.valueOf(arreglo[i].getPoderMax());
            
            modelo.addRow(datos);
            
            
        }
    }
    

}
