/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Paquete.Clases.*;
import Paquete.gestion.Gestion;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class Ventana extends javax.swing.JFrame {

    private Gestion ref;
    
    public Ventana() {
        initComponents();
        ref = new Gestion();
        
    }

    public Gestion getRef() {
        return ref;
    }

    public void setRef(Gestion ref) {
        this.ref = ref;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new ImageFondo();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TextoNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextoNivel = new javax.swing.JTextField();
        TextoFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextoPoder = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RadioAgua = new javax.swing.JRadioButton();
        RadioFuego = new javax.swing.JRadioButton();
        RadioTierra = new javax.swing.JRadioButton();
        RadioPlanta = new javax.swing.JRadioButton();
        RadioPsiqui = new javax.swing.JRadioButton();
        RadioFantasma = new javax.swing.JRadioButton();
        RadioElec = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CheckSi = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POKÉDEX");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        TextoNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNomActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Nivel");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Fecha de adquisición");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("Poder Inicial");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/VerRegistro.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        buttonGroup1.add(RadioAgua);
        RadioAgua.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RadioAgua.setText("Tipo Agua");

        buttonGroup1.add(RadioFuego);
        RadioFuego.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RadioFuego.setText("Tipo Fuego");
        RadioFuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioFuegoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioTierra);
        RadioTierra.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RadioTierra.setText("Tipo Tierra");

        buttonGroup1.add(RadioPlanta);
        RadioPlanta.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RadioPlanta.setText("Tipo Planta");

        buttonGroup1.add(RadioPsiqui);
        RadioPsiqui.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RadioPsiqui.setText("Tipo Psíquico");

        buttonGroup1.add(RadioFantasma);
        RadioFantasma.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RadioFantasma.setText("Tipo Fantasma");

        buttonGroup1.add(RadioElec);
        RadioElec.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RadioElec.setText("Tipo Eléctrico");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Ingresa1.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(1, 123, 200));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("AGREGAR");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("¿Posee piedra evolutiva?");

        CheckSi.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CheckSi.setText("Sí");
        CheckSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(122, 122, 122)
                        .addComponent(CheckSi))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(81, 81, 81))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(40, 40, 40)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextoPoder, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(TextoNivel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TextoFecha, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(42, 42, 42)
                            .addComponent(TextoNom))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioPsiqui, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RadioAgua)
                            .addComponent(RadioTierra))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioFantasma)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(RadioPlanta)
                                .addComponent(RadioFuego)))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RadioElec)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioFuego)
                            .addComponent(RadioAgua))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioPlanta)
                            .addComponent(RadioTierra))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioPsiqui)
                            .addComponent(RadioFantasma))
                        .addGap(18, 18, 18)
                        .addComponent(RadioElec)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TextoNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CheckSi))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNomActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        MostrarTable tabla = new MostrarTable();
        tabla.setRef2(ref);
        tabla.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void RadioFuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioFuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioFuegoActionPerformed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(37,169,214));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(1,123,200));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
if(ref.getPuntero()<ref.getArreglo().length){        
        String nombre = this.TextoNom.getText();
        int nivel = Integer.parseInt(this.TextoNivel.getText());
        String fecha = this.TextoFecha.getText();
        int poderInicial = Integer.parseInt(this.TextoPoder.getText());
        boolean Piedra = false;
        if(CheckSi.isSelected()==true){
            Piedra = true;
        }
        
        
        if(this.RadioAgua.isSelected())
        {
            TipoAgua refTA = new TipoAgua(nombre,nivel,fecha,poderInicial);
            refTA.CalcularPoderMaximo();
            refTA.VerificarSiEsShiny();
            refTA.EvolucionarElemen();
            ref.Ingresar(refTA);
        }
        else if(this.RadioFuego.isSelected())
        {
            TipoFuego refTF = new TipoFuego(nombre,nivel,fecha,poderInicial);
            refTF.CalcularPoderMaximo();
            refTF.VerificarSiEsShiny();
            refTF.EvolucionarElemen();
            ref.Ingresar(refTF);
        }
        else if(this.RadioTierra.isSelected())
        {
            TipoTierra refTT = new TipoTierra(nombre,nivel,fecha,poderInicial);
            refTT.CalcularPoderMaximo();
            refTT.VerificarSiEsShiny();
            refTT.EvolucionarElemen();
            ref.Ingresar(refTT);
        }
        else if(this.RadioPlanta.isSelected())
        {
            TipoPlanta refTP = new TipoPlanta(nombre,nivel,fecha,poderInicial);
            refTP.CalcularPoderMaximo();
            refTP.VerificarSiEsShiny();
            refTP.EvolucionarElemen();
            ref.Ingresar(refTP);
        }
        else if(this.RadioElec.isSelected())
        {
            TipoElectrico refTE = new TipoElectrico(nombre,nivel,fecha,poderInicial);
            refTE.CalcularPoderMaximo();
            refTE.VerificarSiEsShiny();
            refTE.EvolucionarElemen();
            ref.Ingresar(refTE); 
        }
        else if(this.RadioPsiqui.isSelected())
        {  
            TipoPsiquico refTPs = new TipoPsiquico(Piedra,nombre,nivel,fecha,poderInicial);
            refTPs.CalcularPoderMaximo();
            refTPs.VerificarSiEsShiny();
            refTPs.EvolucionarEspecial();
            ref.Ingresar(refTPs);          
        }
        else if(this.RadioFantasma.isSelected())
        {
            TipoFantasma refTFan = new TipoFantasma(Piedra,nombre,nivel,fecha,poderInicial);
            refTFan.CalcularPoderMaximo();
            refTFan.VerificarSiEsShiny();
            refTFan.EvolucionarEspecial();
            ref.Ingresar(refTFan);
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione el tipo de Pokémon");
        }
    }else{
            JOptionPane.showMessageDialog(null, "No hay espacio");
        }            
    }//GEN-LAST:event_jLabel7MouseClicked

    private void CheckSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckSiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckSi;
    private javax.swing.JRadioButton RadioAgua;
    private javax.swing.JRadioButton RadioElec;
    private javax.swing.JRadioButton RadioFantasma;
    private javax.swing.JRadioButton RadioFuego;
    private javax.swing.JRadioButton RadioPlanta;
    private javax.swing.JRadioButton RadioPsiqui;
    private javax.swing.JRadioButton RadioTierra;
    private javax.swing.JTextField TextoFecha;
    private javax.swing.JTextField TextoNivel;
    private javax.swing.JTextField TextoNom;
    private javax.swing.JTextField TextoPoder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    class ImageFondo extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("FondoPokedex.jpeg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
        
        
    }


}
